development:
  adapter: mysql2
  encoding: utf8
  database: sample_rails5_app_development
  pool: 5
  username: postgres
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: sample_rails5_app_test
  pool: 5
  username: postgres
  password:
