development:
  adapter: postgresql
  encoding: unicode
  database: sample_rails5_app_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_rails5_app_test
  pool: 5
  username: postgres
  password:
