# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a4f7669715c40cd2f03b1ed8bdfeeeec9b3547dcd95d60ecbdff24ad16c6c32f8928eacba7ec078e91077c1280a5c8b0ddc258f6ae92a53174a3fee64c212c

test:
  secret_key_base: 1744f2b2acf423e5697dc75fd415f68601ad09e0ca6225132190a5f50d6512cd2c8e2db7172dfe7c5bc95de6c2f79d1786a97fcfc15c948af190d804a18bc10d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
